// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUmpTr3r3gfn7erG-KYPMoUXXbseVPOSs',
    appId: '1:1097187251228:web:b566ca1738d94d0a63fbd9',
    messagingSenderId: '1097187251228',
    projectId: 'slock-bb631',
    authDomain: 'slock-bb631.firebaseapp.com',
    databaseURL: 'https://slock-bb631-default-rtdb.firebaseio.com',
    storageBucket: 'slock-bb631.firebasestorage.app',
    measurementId: 'G-PBRC6Y54W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYi7bYr50mBfGE3FrZBJ-HzN-tN31CcT0',
    appId: '1:1097187251228:android:6e5cb2a0060489c063fbd9',
    messagingSenderId: '1097187251228',
    projectId: 'slock-bb631',
    databaseURL: 'https://slock-bb631-default-rtdb.firebaseio.com',
    storageBucket: 'slock-bb631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC24F6ODfuDzC8gA_ObZM62ztjYkeUBDpI',
    appId: '1:1097187251228:ios:5f22902ef03cde8d63fbd9',
    messagingSenderId: '1097187251228',
    projectId: 'slock-bb631',
    databaseURL: 'https://slock-bb631-default-rtdb.firebaseio.com',
    storageBucket: 'slock-bb631.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC24F6ODfuDzC8gA_ObZM62ztjYkeUBDpI',
    appId: '1:1097187251228:ios:5f22902ef03cde8d63fbd9',
    messagingSenderId: '1097187251228',
    projectId: 'slock-bb631',
    databaseURL: 'https://slock-bb631-default-rtdb.firebaseio.com',
    storageBucket: 'slock-bb631.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUmpTr3r3gfn7erG-KYPMoUXXbseVPOSs',
    appId: '1:1097187251228:web:f12b2cd61008587063fbd9',
    messagingSenderId: '1097187251228',
    projectId: 'slock-bb631',
    authDomain: 'slock-bb631.firebaseapp.com',
    databaseURL: 'https://slock-bb631-default-rtdb.firebaseio.com',
    storageBucket: 'slock-bb631.firebasestorage.app',
    measurementId: 'G-43PV97714T',
  );
}
